In [1]:
import numpy as np
test_array = np.array([1 , 4 , 5 , 8] , float)
test_array

array([1., 4., 5., 8.])

In [2]:
type(test_array[3])

numpy.float64

In [3]:
# 배열

matrix = [[1,2,5,8,] , [1,2,5,8] , [1,2,5,8]]
np.array(matrix , int).shape

(3, 4)

In [7]:
x = np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
x.reshape(2 , 4) # reshape를 할때 두 인수로 주는 두 수를 곱한 값이 원래 원소의 개수와 같아야 한다.

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
x.reshape(4 , -1) # -1을 줄 경우 알아서 맞게 하라는 인수이다.

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [17]:
x = np.array(range(8)).reshape(2 , 2 , 2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [18]:
x.flatten() #1차원으로 만들어준다.

array([0, 1, 2, 3, 4, 5, 6, 7])

In [23]:
# 인덱싱

x = np.array([[1 , 2 , 3 , 4 , 5] , [6 , 7 , 8 , 9 , 10]] , int)
x[:,2:] # 행 전체와 열은 2번째부터 마지막까지

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [26]:
x = np.array(range(15) , int).reshape(3 , -1)
x[: , ::2] # 2개씩 증가하게 한다.

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [27]:
x[::2 , ::3]

array([[ 0,  3],
       [10, 13]])

In [31]:
np.arange(10)
np.arange(-5 ,5)
np.arange(0 , 5 , 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [36]:
# ones_like , zeros_like , empty_like

x = np.arange(12).reshape(3 , 4)
x
np.ones_like(x)
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [37]:
# 넘파이 통계 분석 함수

# uniform 함수 : 균등분포함수
np.random.uniform(0 , 5 , 10)

array([1.50135151, 4.39250055, 0.2869545 , 4.0212221 , 2.17544748,
       2.24589136, 3.76972556, 1.20798236, 2.71043403, 3.8766657 ])

In [38]:
# normal 함수 : 정규분포 함수
np.random.normal(0 , 2 , 10)

array([-0.75418439,  4.2360806 , -1.54565989,  0.59080831,  1.08541622,
       -1.76666739,  2.76586401, -2.68756767, -0.71945127, -0.60665248])

In [39]:
# 1. 연산 함수

test_array = np.arange(1 , 11)
test_array.sum()

55

In [42]:
test_array = np.arange(1 , 13).reshape(3 , 4)
test_array

test_array.sum(axis = 0)
test_array.sum(axis = 1)

array([10, 26, 42])

In [43]:
test_array = np.arange(1 , 13).reshape(3 , 4)
third_order_tensor = np.array([test_array , test_array , test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [47]:
third_order_tensor.sum(axis = 0)

third_order_tensor.sum(axis = 1)

third_order_tensor.sum(axis = 2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [50]:
test_array = np.arange(1 , 13).reshape(3 , 4)
test_array

test_array.mean(axis = 1)

test_array.std()

3.452052529534663

In [52]:
test_array.std(axis = 0)

np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])