In [1]:
# 연결 함수

# 연결 함수 : 두 객체 간의 결합을 지원하는 함수

import numpy as np

v1 = np.array([1 , 2 , 3])
v2 = np.array([4 , 5 , 6])
np.vstack((v1 , v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
# vstack -> 상하로 연결
# hstack -> 좌우로 연결
np.hstack((v1 ,v2))

array([1, 2, 3, 4, 5, 6])

In [4]:
v1 = v1.reshape(-1 , 1)
v2 = v2.reshape(-1 , 1)

array([[4],
       [5],
       [6]])

In [7]:
# concatenamte 함수

v1 = np.array([[1 , 2 , 3]])
v2 = np.array([[4 , 5 , 6]])
np.concatenate((v1 , v2) , axis = 0)

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
v1 = np.array([1 , 2 , 3 , 4]).reshape(2 , 2)
v2 = np.array([[5 , 6]]).T
v1

array([[1, 2],
       [3, 4]])

In [11]:
v2

array([[5],
       [6]])

In [12]:
np.concatenate((v1 , v2) , axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [14]:
# 배열 간 사칙연산 지원

x = np.arange(1 , 7).reshape(2 , 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
x + x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [16]:
x - x

array([[0, 0, 0],
       [0, 0, 0]])

In [17]:
x / x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
x ** x

array([[    1,     4,    27],
       [  256,  3125, 46656]])

In [23]:
# 비교 연산과 데이터 추출

x = np.array([1 , 3 , 0])
y = np.array([2 , 1 , 7])

x > y

array([False,  True, False])

In [26]:
(x > 1).all()

False

In [25]:
(x >= 3).any()

True

In [27]:
(x < 10).any()

True

In [29]:
np.where(x > 2)

(array([1], dtype=int64),)

In [30]:
# 정렬된 값의 인덱스를 반환해주는 함수

# argsort : 배열 내 값들을 작은 순서대로 인덱스를 반환
# argmax : 배열 내 값들 중 가장 큰 값의 인덱스를 반환
# argmin : 뱅려 내 값들 중 가장 작은 값의 인덱스를 반환

x = np.array([4 , 6 , 7 , 3 , 2])
np.argsort(x) # 반환 값은 인덱스 값이다.

array([4, 3, 0, 1, 2], dtype=int64)